# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site Settings

title: Core Interaction Spring 2018
email: hermonn@newschool.edu
description: >-
  Core Interaction Spring 2018
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ci.vv6.co" #base hostname & protocol

# Build settings

sass:
  sass_dir: assets/css/_partials

markdown: kramdown
plugins: [ "jekyll-feed" ]

# Define data collections
collections:
  assignments:
    output: true
    permalink: /:collection/:title.html
  lectures:
    output: true
    permalink: /:collection/:title.html

defaults:
  - scope:
      path: ""
      type: assignments
    values:
      layout: post-detail
      type: assignment
  - scope:
      path: ""
      type: lectures
    values:
      layout: post-detail
      type: lecture

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude: [ "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/" ]
