# Site Settings

title: Core Interaction Spring 2018
email: hermonn@newschool.edu
description: >-
  Core Interaction Spring 2018
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ci.vv6.co" #base hostname & protocol

# Build settings

sass:
  sass_dir: assets/css/_partials

markdown: kramdown
highlighter: rouge

plugins: [ "jekyll-feed" ]

# Define data collections
collections:
  assignments:
    output: true
    permalink: /:collection/:title.html
  lectures:
    output: true
    permalink: /:collection/:title.html

defaults:
  - scope:
      path: ""
      type: assignments
    values:
      layout: post-detail
      type: assignment
  - scope:
      path: ""
      type: lectures
    values:
      layout: post-detail
      type: lecture

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude: [ "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/" ]
